### ISSUE TITLE
Feature request - expose keys to allow for explicit naming of resources

### ISSUE THREAD

**Issue by gitet** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit#16]
Hi! Thanks for providing this excellent module - it really makes life much easier (and my code cleaner) to work with these abstractions :-)

There's an important feature that I'd like to see added to this module (and the rest of the modules as well, where applicable). 

Here goes:

Our internal governance model has naming conventions that we would very much like to adhere to. 
The current version (2.5.1) of the `mc-transit` module will not allow us to do so, since it does not seem to expose the keys needed for setting the following explicitly:

* the name of the VPC being created, or to use an already existing VPC
* the name of the VM hosting the transit gateways (something similar to what can be done with `custom_fw_names` in the `mc-firenet` module would be handy)
* Ideally, the modules should allow us to set all resource names explicitly (at least the following: resource group name, vnet name, vm names), overriding any implicit prefix or suffix "padding" of the names - something I find to a bit of an anti-pattern to be honest.

Cool if you'd find the time to look into this feature request. I'd hate to have to create my own "home-grown" version of the module to pull it off :-)

Thanks
BR/Espen

**Comment by ragaaviatrix** [comment]
Hi Espen,

You can set the name of the VPC/VNET/gateway like below:

`  name                             = "dev_vpc_aws"
  gw_name                        = "dev_gateway_aws`

**Comment by gitet** [comment]
Hi Raga,

I'm not quite sure how I missed the `name` key to be honest, thanks for the help and the extra set of eyes! :-)
Would be nice if `use_existing_vpc` etc. was exposed all the way up though.

Yes, I am setting the `resource_group` key and also using `gw_name` to set the resource name as seen from the controller, but the azure resource will have prefix padding `av-gw-` (something we can live with, but is not a nice fit for our naming conventions.  Alternatively, for us, changing the "padding" from prefix to suffix would work.

**Comment by ragaaviatrix** [comment]
Hi Espen,

I am glad it helped. Please note that we expose `use_existing_vpc` for mc-spoke modules. For mc-transit modules, it's our design requirement to create the transit VPC using the controller. Hence, you do not see it in the module.

**Comment by Dennizz** [comment]
Hi Espen,

FYI, `av-gw-` is prepended by the controller, so unfortunatly not something I can address in the module.

Currently no existing VPC is supported for this transit module indeed, as the aviatrix_vpc resource we use for that is pretty prescriptive. I have come across a valid reason to support byo VNET recently though (enabling DDoS) so I may implement it in the future. It's pretty tricky though, as you would have to either construct the VNET a specific way or I would need you to feed all subnet references explicitly. Neither of which is ideal. Also, at that point writing your own module with mixed resources (azurerm + aviatrix) may be a better way than trying to catch all use cases in this module. I cannot leverage the providers for native resources in this generic module, as I can not instantiate them conditionally. As you can see, I need to spend some time thinking about the best way to address this, while maintaining compatibility for all other scneario's.

I'll go ahead and close this one, assuming it answered all your questions.
