### ISSUE TITLE
Please add approved_learned_cidrs to the module parameters

### ISSUE THREAD

**Issue by alexandreweiss** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit#17]
Hi,

Could you please make the "approved_learned_cidrs" configurable from the module so we can add CIDRs to auto approve.

Thanks

https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/resources/aviatrix_transit_gateway#approved_learned_cidrs

**Comment by Dennizz** [comment]
@fkhademi just added this and was merged. Will be part of the next release.

**Comment by alexandreweiss** [comment]
Thanks Dennis !!
