### ISSUE TITLE
lifecycle ignore for tags

### ISSUE THREAD

**Issue by ragaaviatrix** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit#21]
Can you please add the lifecycle ignore block for tags? When the gateways are created with tags, the customer environment has some automation that adds additional tags when the EC2 instances are launched. When the customer adds some config to the terraform file (say a new module for another region) and tries an apply, the plan shows that the additional tags will be deleted (as they werent present initially and were added out of band by the automation)

**Comment by Dennizz** [comment]
Closing after off-line deliberation.
