### ISSUE TITLE
Can't create AliCloud VPC due to VPC/VNet name cannot exceed 30 characters

### ISSUE THREAD

**Issue by jwang-avx** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit#3]
Alicloud region used in aviatrix_vpc resource is different than the official Alicloud region name.
For example, region "acs-us-east-1 (Virginia)" maps to "us-east-1".
If we use "acs-us-east-1 (Virginia)" to create VPC, it will fail with the following error:
```
Error: failed to create a new Aviatrix Transit VPC: rest API create_custom_vpc Post failed: [AVXERR-TOOLS-0029] VPC/VNet name cannot exceed 30 characters
```

**Comment by Dennizz** [comment]
Thanks for reporting this. A patch has been applied, which will be part of the 2.1.3 version release. For now, you can overcome this by manually providing a name.

e.g.
```
module "aws_transit" {
  source  = "terraform-aviatrix-modules/mc-transit/aviatrix"
  version = "2.0.2"

  name = "my_name"
  ...
}
```
