### ISSUE TITLE
Terraform Error on "enable_bgp_over_lan" for AWS

### ISSUE THREAD

**Issue by mbockmannsva** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit#6]
Release: v2.1.6 

When using the variable "enable_bp_over_lan for Cloud Provider AWS following error is occuring:

"Error: 'enable_bgp_over_lan' is only valid for GCP (4), Azure (8), AzureGov (32) or AzureChina (2048)".

Documentation states that AWS is supported. There are no thurther information for release v2.2.0 which states that this is a new feature.

**Comment by Dennizz** [comment]
Looks like a module documentation error. Thanks for raising this. Will address this soon.

When in doubt, provider documentation is always leading:
https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/resources/aviatrix_transit_gateway#bgp-over-lan

**Comment by Dennizz** [comment]
Addressed in v2.2.1
