### ISSUE TITLE
enable_dns_server and ha_subnet arguments not supported in mc-transit

### ISSUE THREAD

**Issue by JakubD-AVX** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit#9]
Hello,
The customer (Yara) is using our Aviatrix resources in Terraform.
The customer would like to "migrate" from resources to mc-modules.

We have been working currently on the mc-transit module and we faced an issue with the following two arguments:
**- enabled_vpc_dns_server
- ha_subnet**
We are not able to set up values for those two arguments.

Therefore, TF Plan shows they will be changed.

I would like to ask you to adjust the mc-transit module and accommodate those two arguments.

**Comment by Dennizz** [comment]
enable_vpc_dns_server added in 2.4.1

**Comment by Dennizz** [comment]
ha_subnet no longer seems required.
